main = "workers-site/index.js"
name = "simple-ip-site"
workers_dev = true
compatibility_date = "2021-10-27"
site = { bucket = "./public" }
vars = { ENVIRONMENT = "production" }

[env.dev]
name = "simple-ip-site-dev"
vars = { ENVIRONMENT = "dev" }
