name: Deploy to Cloudflare Workers
on:
  repository_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "*.md"
      - ".github/workflows/*"
      - "alt.simpleip.de/*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - name: Check out Git repo
        uses: actions/checkout@v3
      - name: Build and Publish with Wrangler
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
