name: Test Build
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build only
    steps:
      - name: Check out Git repo
        uses: actions/checkout@v2
      - name: Build with Wrangler
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: wrangler build
          environment: dev
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
